### ISSUE TITLE
How to publish bboxed image?

### ISSUE THREAD

**Issue by kyuhyong** [Ar-Ray-code/YOLOv5-ROS#3]
I am trying to publish images with bounding boxes as ros msg.
To do so, I modified **def image_callback(self, image_raw):** in main.py to return im0 as below
```
            # Stream results
            im0 = annotator.result()
            if self.view_img:
                cv2.imshow("yolov5", im0)
                cv2.waitKey(1)  # 1 millisecond

            return class_list, confidence_list, x_min_list, y_min_list, x_max_list, y_max_list, im0
```

and in **image_callback** in yolov5_ros I modified publisher as below
```
    def image_callback(self, image:Image):
        image_raw = self.bridge.imgmsg_to_cv2(image, "bgr8")
        # return (class_list, confidence_list, x_min_list, y_min_list, x_max_list, y_max_list)
        class_list, confidence_list, x_min_list, y_min_list, x_max_list, y_max_list, yolo_img = self.yolov5.image_callback(image_raw)

        msg = self.yolovFive2bboxes_msgs(bboxes=[x_min_list, y_min_list, x_max_list, y_max_list], scores=confidence_list, cls=class_list, img_header=image.header)
        self.pub_bbox.publish(msg)
        yolo_img = self.bridge.cv2_to_imgmsg(yolo_img, "bgr8")
        self.pub_image.publish(yolo_img)
```

However I am still getting image without any bounding boxes. What am I missing here?

**Comment by Ar-Ray-code** [comment]
I created new branch publishing image with bounding boxes instead of input image.

Please check the differences.

https://github.com/Ar-Ray-code/YOLOv5-ROS/tree/issue_ans/output_img_with_bboxes

**Comment by Ar-Ray-code** [comment]
In that branch, we have confirmed that it can be displayed using rqt_graph.
Does this satisfy your issue?

![Screenshot from 2022-06-25 23-54-26](https://user-images.githubusercontent.com/67567093/175779398-f0f82424-803d-4fac-99df-e530b04f682b.png)

**Comment by Ar-Ray-code** [comment]
There is no clear difference between the code you described and the diff I showed, so maybe you need to reload your build and environment.

**Comment by kyuhyong** [comment]
I am still not getting image with bboxes as shown above.
rqt_image_view shows just same as camera image. 
Maybe I didn't build install the package in the host system and only running the package in remote?

Anyway I forked the package and once everything looks good, I will pull request.
Thanks,
